variable bastion_ami {}
variable bastion_instance_type {}
variable key_name {}
variable bastion_mgmt_subnet_id {}
variable bastion_data_subnet_id {}
variable bastion_security_group_ids {}
variable bastion_instance_name {}
variable region {}
variable access_key_id {}
variable secret_key {}
variable "iam_role_name" {}